name: Check all

on:
  - push
  - pull_request

jobs:
  check-all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format only
        uses: cpp-linter/cpp-linter-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy: false
          clang_format: true

